<a href="https://colab.research.google.com/github/MegaTunji/neural-network-challenge-2/blob/main/attrition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [2]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]
y_df



Attrition              Department
0          Yes                   Sales
1           No  Research & Development
2          Yes  Research & Development
3           No  Research & Development
4           No  Research & Development
...        ...                     ...
1465        No  Research & Development
1466        No  Research & Development
1467        No  Research & Development
1468        No                   Sales
1469        No  Research & Development

[1470 rows x 2 columns]

In [4]:
# Create a list of at least 10 column names to use as X data
sel_x_columns =  ['Age', 'Education','HourlyRate','DistanceFromHome',
                               'OverTime','StockOptionLevel','WorkLifeBalance' ,'YearsAtCompany',
                               'YearsSinceLastPromotion','NumCompaniesWorked']




# Create X_df using your selected columns
X_df = attrition_df[sel_x_columns]


# Show the data types for X_df
X_df.info()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Age                      1470 non-null   int64 
 1   Education                1470 non-null   int64 
 2   HourlyRate               1470 non-null   int64 
 3   DistanceFromHome         1470 non-null   int64 
 4   OverTime                 1470 non-null   object
 5   StockOptionLevel         1470 non-null   int64 
 6   WorkLifeBalance          1470 non-null   int64 
 7   YearsAtCompany           1470 non-null   int64 
 8   YearsSinceLastPromotion  1470 non-null   int64 
 9   NumCompaniesWorked       1470 non-null   int64 
dtypes: int64(9), object(1)
memory usage: 115.0+ KB


In [5]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_test, X_train, y_test, y_train = train_test_split(X_df, y_df, test_size=0.2, random_state=42)



In [6]:
from sklearn.preprocessing import OneHotEncoder
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
overtime_encode = OneHotEncoder(sparse_output = False, drop = 'first', handle_unknown= 'ignore')
overtime_encode.fit(np.array(X_train['OverTime']).reshape(-1,1))

X_train["Overtime_Encoded"]= overtime_encode.transform(np.array(X_train['OverTime']).reshape(-1,1))
X_test["Overtime_Encoded"]= overtime_encode.transform(np.array(X_test['OverTime']).reshape(-1,1))

X_train = X_train.drop(columns='OverTime')
X_test = X_test.drop(columns='OverTime')

In [8]:
# Double check X_train columns
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 294 entries, 1041 to 651
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Age                      294 non-null    int64  
 1   Education                294 non-null    int64  
 2   HourlyRate               294 non-null    int64  
 3   DistanceFromHome         294 non-null    int64  
 4   StockOptionLevel         294 non-null    int64  
 5   WorkLifeBalance          294 non-null    int64  
 6   YearsAtCompany           294 non-null    int64  
 7   YearsSinceLastPromotion  294 non-null    int64  
 8   NumCompaniesWorked       294 non-null    int64  
 9   Overtime_Encoded         294 non-null    float64
dtypes: float64(1), int64(9)
memory usage: 25.3 KB


In [10]:
# value count of yes and no in Overtime_Encoded
X_train["Overtime_Encoded"].value_counts()

Overtime_Encoded
0.0    217
1.0     77
Name: count, dtype: int64

In [ ]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
#X_train['OverTime'] = X_train['OverTime'].map({'Yes': 1, 'No': 0})
#X_test['OverTime'] = X_test['OverTime'].map({'Yes': 1, 'No': 0})

#Check value counts
#X_train['OverTime'].value_counts()
#X_test['OverTime'].value_counts()

OverTime
0    837
1    339
Name: count, dtype: int64

In [11]:
# Check X_test for new column name
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1176 entries, 1097 to 1126
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Age                      1176 non-null   int64  
 1   Education                1176 non-null   int64  
 2   HourlyRate               1176 non-null   int64  
 3   DistanceFromHome         1176 non-null   int64  
 4   StockOptionLevel         1176 non-null   int64  
 5   WorkLifeBalance          1176 non-null   int64  
 6   YearsAtCompany           1176 non-null   int64  
 7   YearsSinceLastPromotion  1176 non-null   int64  
 8   NumCompaniesWorked       1176 non-null   int64  
 9   Overtime_Encoded         1176 non-null   float64
dtypes: float64(1), int64(9)
memory usage: 101.1 KB


In [12]:
# Create a StandardScaler
scaler = StandardScaler()


# Fit the StandardScaler to the training data
scaler.fit(X_train)


# Scale the training and testing data
scaled_Xtrain = scaler.transform(X_train)
scaled_Xtest = scaler.transform(X_test)


In [13]:
# read y_train data
y_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 294 entries, 1041 to 651
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Attrition   294 non-null    object
 1   Department  294 non-null    object
dtypes: object(2)
memory usage: 6.9+ KB


In [14]:
# Create a OneHotEncoder for the Department column
dept_encode = OneHotEncoder(sparse_output= False, drop= None, handle_unknown = 'ignore')


# Fit the encoder to the training data
dept_encode.fit(np.array(y_train['Department']).reshape(-1,1))


# Create two new variables by applying the encoder
# to the training and testing data
y_dept_train_encode = dept_encode.transform(np.array(y_train['Department']).reshape(-1,1))
y_dept_test_encode = dept_encode.transform(np.array(y_test['Department']).reshape(-1,1))

In [15]:
# Create a OneHotEncoder for the Department column
#encode_dept= OneHotEncoder(sparse_output= False)

# Fit the encoder to the training data
#encode_dept.fit(y_train[['Department']])


# Create two new variables by applying the encoder
# to the training and testing data
#y_train_dept_encoded = encode_dept.transform(y_train[['Department']])
#y_test_dept_encoded = encode_dept.transform(y_test[['Department']])


#print(y_train_dept_encoded)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0.

In [21]:
# Create a OneHotEncoder for the Attrition column
encoded_attr = OneHotEncoder(sparse_output= False, drop = 'first', handle_unknown= 'ignore' )

# Fit training data
encoded_attr.fit(np.array(y_train['Attrition']).reshape(-1,1))





# Create two new variables by applying the encoder
# to the training and testing data
y_train_encoded_attr = encoded_attr.transform(np.array(y_train['Attrition']).reshape(-1, 1))
y_test_attr_encode = encoded_attr.transform(np.array(y_test['Attrition']).reshape(-1,1))

# Display y_train_encoded_attr
y_train_encoded_attr[:5]








array([[0.],
       [0.],
       [1.],
       [0.],
       [0.]])

## Create, Compile, and Train the Model

In [22]:
# Find the number of columns in the X training data and print.
num_of_columns = scaled_Xtrain.shape[1]

print(f'The number of columns in the X training:{num_of_columns}')


The number of columns in the X training:10


In [23]:

#Create the input layer
input_layer = layers.Input(shape=(num_of_columns,))


# Create at least two shared layers
shared1_layer = layers.Dense(64, activation = 'relu')(input_layer)
shared2_layer = layers.Dense(32, activation= "relu")(shared1_layer)


In [25]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
dept_hidden_layer = layers.Dense(16, activation = "relu")(shared2_layer)


# Create the output layer
output_dept = layers.Dense(y_dept_train_encode.shape[1], activation= 'softmax', name = "output_dept")(dept_hidden_layer)



In [30]:
y_df

Attrition              Department
0          Yes                   Sales
1           No  Research & Development
2          Yes  Research & Development
3           No  Research & Development
4           No  Research & Development
...        ...                     ...
1465        No  Research & Development
1466        No  Research & Development
1467        No  Research & Development
1468        No                   Sales
1469        No  Research & Development

[1470 rows x 2 columns]

In [31]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attr_hidden_layer = layers.Dense(16, activation='relu')(shared2_layer)


# Create the output layer
output_attr = layers.Dense(y_train_encoded_attr.shape[1],activation = 'sigmoid', name = 'output_attr')(attr_hidden_layer)



In [32]:
# Create the model
model = Model(inputs = input_layer, outputs= [output_attr, output_dept])

# Compile the model
model.compile(optimizer = 'adam',
              loss ={'output_dept': 'categorical_crossentropy',
                    'output_attr': 'binary_crossentropy'}
              , metrics ={'output_dept': 'accuracy',
              'output_attr': 'accuracy'})

# Summarize the model
model.summary()


Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)  │ (None, 10)             │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense (Dense)             │ (None, 64)             │            704 │ input_layer[0][0]      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_1 (Dense)           │ (None, 32)             │          2,080 │ dense[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_4 (Dense)           │ (None, 16)             │            528 │ dense_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_3 (Dense)           │ (None, 16)             │            528 │ dense_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ output_attr (Dense)       │ (None, 1)              │             17 │ dense_4[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ output_dept (Dense)       │ (None, 3)              │             51 │ dense_3[0][0]          │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 3,908 (15.27 KB)

 Trainable params: 3,908 (15.27 KB)

 Non-trainable params: 0 (0.00 B)

In [34]:
from re import VERBOSE
# Train the model
history = model.fit(scaled_Xtrain,
                [y_train_encoded_attr, y_dept_train_encode],
                epochs=100,
                batch_size=32,
                validation_split =.2,
                verbose= 2

                )




Epoch 1/100
8/8 - 0s - 26ms/step - loss: 1.1356 - output_attr_accuracy: 0.8553 - output_dept_accuracy: 0.6638 - val_loss: 1.0963 - val_output_attr_accuracy: 0.9153 - val_output_dept_accuracy: 0.6780
Epoch 2/100
8/8 - 0s - 14ms/step - loss: 1.1192 - output_attr_accuracy: 0.8553 - output_dept_accuracy: 0.6638 - val_loss: 1.0912 - val_output_attr_accuracy: 0.9153 - val_output_dept_accuracy: 0.6780
Epoch 3/100
8/8 - 0s - 13ms/step - loss: 1.1062 - output_attr_accuracy: 0.8553 - output_dept_accuracy: 0.6638 - val_loss: 1.0897 - val_output_attr_accuracy: 0.9153 - val_output_dept_accuracy: 0.6780
Epoch 4/100
8/8 - 0s - 11ms/step - loss: 1.0966 - output_attr_accuracy: 0.8553 - output_dept_accuracy: 0.6681 - val_loss: 1.0882 - val_output_attr_accuracy: 0.9153 - val_output_dept_accuracy: 0.6780
Epoch 5/100
8/8 - 0s - 15ms/step - loss: 1.0813 - output_attr_accuracy: 0.8553 - output_dept_accuracy: 0.6723 - val_loss: 1.0765 - val_output_attr_accuracy: 0.9153 - val_output_dept_accuracy: 0.6780
Epoch

In [35]:
# Evaluate the model with the testing data
evaluation = model.evaluate(scaled_Xtest,
                            [y_dept_test_encode, y_test_attr_encode], return_dict =True)

37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3.9392 - output_attr_accuracy: 0.6364 - output_dept_accuracy: 0.0177  


In [36]:
# Print the accuracy for both department and attrition
evaluation

{'loss': 4.1175103187561035,
 'output_attr_accuracy': 0.6340702772140503,
 'output_dept_accuracy': 0.010204081423580647}

# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not? NO because the accuracy of predicting the department is sigificantly low and thus would not provide the intended use and this may be due to class inbalance.

2. What activation functions did you choose for your output layers, and why? For y data Department I choose the 'softmax' activation due to its multi label classification and sigmoid for attrition pair with binary crossentrop for binary classifcaition in this case 'yes or 'no'.

3. Can you name a few ways that this model might be improved? The model can be improved by checking for the inbalances and adding more layers and or adjusting the training measures.

YOUR ANSWERS HERE

1.
2.
3.